Fix DevContainer Python deps and build speed
TGSAI/mdio-cpp pull request #73
Opened 2024-08-05 21:36 UTC by BrianMichell

Resolves #68

- Pip now installs Zarr and Xarray
- We now grab the compiled binary for CMake. This is a big speed-up for new builds.

2024-08-07 17:32 UTC, blasscoc requested changes
If we have pyproject.toml, just use poetry in the dev container

2024-08-07 17:49 UTC, BrianMichell commented
@markspec could probably set up the full pyproject.toml. We don't have one right now.

2024-08-20 12:41 UTC, brian-michell approved these changes

2024-08-20 12:58 UTC, brian-michell approved these changes

2024-08-20 16:21 UTC, markspec approved these changes
LGTM

2024-08-20 16:21 UTC, merged